//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string NICK_CLIENTE { get; set; }
        public string PASSWORD_CLIENTE { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string ESTADO { get; set; }
    }
}
