//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class IMAGEN
    {
        public int ID_IMAGEN { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
        public string RUTA_IMAGEN { get; set; }
    
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
