//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN
    {
        public int ID_IMAGEN { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
        public string RUTA_IMAGEN { get; set; }
    
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
