//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MARCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MARCA()
        {
            this.MODELO = new HashSet<MODELO>();
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public int ID_MARCA { get; set; }
        [Display(Name = "Nombre de marca")]
        [Required, StringLength(15, MinimumLength = 2)]
        [RegularExpression("[a-zA-Z ·ÈÌÛ˙Ò¡…Õ”⁄—]+$", ErrorMessage = "Este campo solo acepta letras")]
        public string NOMBRE_MARCA { get; set; }
        [Required]
        [Display(Name = "Estado"), StringLength(8, MinimumLength = 6)]
        [RegularExpression("^(ACTIVO|INACTIVO)$", ErrorMessage = "Este campo solo acepta los valores ACTIVO o INACTIVO")]
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODELO> MODELO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
