//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MODELO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELO()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public int ID_MODELO { get; set; }
        [Display(Name = "Nombre de modelo"), StringLength(15, MinimumLength = 1)]
        [Required]
        [RegularExpression("[a-zA-Z0-9 ·ÈÌÛ˙Ò¡…Õ”⁄—]+$", ErrorMessage = "Este campo solo acepta letras y n˙meros")]
        public string NOMBRE_MODELO { get; set; }
        [Required]
        [Display(Name = "Nombre de marca")]
        public Nullable<int> ID_MARCA { get; set; }
        [Display(Name = "Estado"), StringLength(8, MinimumLength = 6)]
        [RegularExpression("^(ACTIVO|INACTIVO)$", ErrorMessage = "Este campo solo acepta los valores ACTIVO o INACTIVO")]
        [Required]
        public string ESTADO { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
