//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PAGINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGINA()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public int ID_PAGINA { get; set; }
        [Display(Name = "Nombre de página"), StringLength(15, MinimumLength = 5)]
        [Required]
        public string NOMBRE_PAGINA { get; set; }
        [Display(Name = "URL de página"), StringLength(15, MinimumLength = 10), DataType(DataType.Url)]
        [Required]
        public string URL_PAGINA { get; set; }
        [Display(Name = "Estado"), StringLength(8, MinimumLength = 6)]
        [Required]
        [RegularExpression("^(ACTIVO|INACTIVO)$", ErrorMessage = "Este campo solo acepta los valores ACTIVO o INACTIVO")]
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
