//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PAGINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGINA()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
       
        public int ID_PAGINA { get; set; }
        [Display(Name = "Nombre de página"), StringLength(15, MinimumLength = 5)]
        [Required]
        public string NOMBRE_PAGINA { get; set; }
        [Display(Name = "URL de página") , StringLength(15, MinimumLength = 10)]
        [Required]
        public string URL_PAGINA { get; set; }
        [Display(Name ="Estado"), StringLength(7, MinimumLength = 6)]
        [Required]
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
