//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.IMAGEN = new HashSet<IMAGEN>();
        }
    
        public int ID_VEHICULO { get; set; }
        public string NO_PLACA { get; set; }
        public int ID_TIPO_VEHICULO { get; set; }
        public int ID_MARCA { get; set; }
        public int ID_MODELO { get; set; }
        public int ID_TIPO_COMBUSTIBLE { get; set; }
        public Nullable<int> PRECIO_VEHICULO { get; set; }
        public int ID_PAGINA { get; set; }
        public string ESTADO { get; set; }
        public string YEAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN> IMAGEN { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
        public virtual PAGINA PAGINA { get; set; }
        public virtual TIPO_COMBUSTIBLE TIPO_COMBUSTIBLE { get; set; }
        public virtual TIPO_VEHICULO TIPO_VEHICULO { get; set; }
    }
}
